language: node_js
node_js:
- v8
script:
- npm run lint && npm test
- npm run build
cache:
- yarn
deploy:
  provider: npm
  skip_cleanup: true
  email: junrai82@gmail.com
  api_key:
    secure: qRUN3FJJufA0qXCCF/Us+rsvJUaKZ0PeMLXvqsZKl7A7e3BQHJkGpM/67s/71q+LMwE3MG7GqZhPHfSjavxTpbRfjc8xH9l8TueTLMIM3IY80jLpiq8BmEARBiWX9Tu/PY7luTwyF2PWqTxxJAdOZRr81krURDmVvzv3+cMfeqXljgrGBKMn32nmzCWiVs7nuPy5hZ75HfbXVoAkuP1+owOvxHnzpzWvPYaNYTh6f1ZNqL8x5m3I4+qNQSFaNklfjX8H64Wwj1kImcvhl/mXBR9pZ/YFuTMw83e7OYmrPOYh8AfwM9j/Q+zg2MjJukPGSrOWGWMB4MMHJZYNv0QNvBVHepMw5p6URcRtczBgqL+1HH7w8fLGcro/GfnEcwXrWFiPYpsfvIDV9kT7fZWQivNuOb1YQBSTywpDqh1aqrV70S90PBijo5Z7k1xFgkeg6e89mzaWiGy32HqCbHYdu1Mq3r7hv+1LA6HRf/55dQ2Aj6NAuWvzEC8lE1K0MutjCQ6pv+iuGItOrn8HaptBcZnKtAi7wlkxo19vZCrgwU/pwTfrwOLbW9NLEjRT4vweK0roVprPS9yczcem6OvsNvBqzb1QwdpaJnM54QyexHLe/pEk/DkATQdoQ1KRUkiC+tPr+ty1RPrcmpqftAauCRDmI47f1ECIYYoB5jMKbiQ=
  on:
    tags: true
    repo: rentspree/version-check
